name: Language Bindings
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: floooh/sokol-zig
          path: bindgen/sokol-zig
      - uses: actions/checkout@v2
        with:
          repository: floooh/sokol-nim
          path: bindgen/sokol-nim
      - name: generate
        run: |
          cd bindgen
          python3 gen_all.py
      - name: upload-zig-artifact
        uses: actions/upload-artifact@v2
        with:
          name: zig-files
          path: bindgen/sokol-zig/src/sokol
          retention-days: 1
      - name: upload-nim-artifact
        uses: actions/upload-artifact@v2
        with:
          name: nim-files
          path: bindgen/sokol-nim/src/sokol
          retention-days: 1

  test-zig:
    needs: generate
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: floooh/sokol-zig
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0
      - uses: actions/download-artifact@v2
        with:
          name: zig-files
          path: src/sokol
      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
      - name: build
        run: zig build

  test-nim:
    needs: generate
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: jiro4989/setup-nim-action@v1
      - uses: actions/checkout@v2
        with:
          repository: floooh/sokol-nim
      - uses: actions/download-artifact@v2
        with:
          name: nim-files
          path: src/sokol
      - if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
      - run: |
          nimble install -Y
          nimble install glm -Y
      # FIXME: this should be solved better
      - if: runner.os == 'Windows'
        run: nim c --cc:vcc examples/cube.nim
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: nim c examples/cube.nim

  # only deploy the bindings for commits on the main branch
  deploy-zig:
    needs: test-zig
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: floooh/sokol-zig
          ssh-key: ${{ secrets.GHACTIONS_ZIG_PUSH }}
      - uses: actions/download-artifact@v2
        with:
          name: zig-files
          path: src/sokol
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git commit -m "updated (https://github.com/floooh/sokol/commit/${{ github.sha }})"
          git push

  deploy-nim:
    needs: test-nim
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: floooh/sokol-nim
          ssh-key: ${{ secrets.GHACTIONS_NIM_PUSH }}
      - uses: actions/download-artifact@v2
        with:
          name: nim-files
          path: src/sokol
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git commit -m "updated (https://github.com/floooh/sokol/commit/${{ github.sha }})"
          git push
